server.port=8080

# ====================== EUREKA ======================
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=true

# ====================== GATEWAY (WebFlux) ======================
spring.cloud.gateway.server.webflux.enabled=true

# Discovery + Load Balancing
spring.cloud.gateway.server.webflux.discovery.locator.enabled=true
spring.cloud.gateway.server.webflux.discovery.locator.lower-case-service-id=true
spring.cloud.gateway.server.webflux.routes[0].uri=lb://user-service

# Route definition
spring.cloud.gateway.server.webflux.routes[0].id=user-service
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/user/**

# Order Service
spring.cloud.gateway.server.webflux.routes[1].uri=lb://order-service
spring.cloud.gateway.server.webflux.routes[1].id=order-service
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/order/**

# Payment Service
spring.cloud.gateway.server.webflux.routes[2].uri=lb://payment-service
spring.cloud.gateway.server.webflux.routes[2].id=payment-service
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/payment/**

#+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

#======== OLD ROUTING CONFIGURATION FOR TRADITIONAL GATEWAY ABOVE IS THE REACTIVE GATEWAY CONFIGURATION ========

#-----> Microservices Routing --> Context path and port numbers

#-----> spring.application.name works as id in microservices
#spring.cloud.gateway.server.webmvc.routes[0].id= user-service
#spring.cloud.gateway.server.webmvc.routes[0].uri= http://localhost:8081
#-----> we put user first because in context path we addded /user means all url start from user will route on this
#-----> if we dont add this we add like /api/users/** in this case
#spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/user/**
#
#spring.cloud.gateway.server.webmvc.routes[1].id= order-service
#spring.cloud.gateway.server.webmvc.routes[1].uri= http://localhost:8082
#spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/order/**
#
#spring.cloud.gateway.server.webmvc.routes[2].id= payment-service
#spring.cloud.gateway.server.webmvc.routes[2].uri= http://localhost:8083
#spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/payment/**
