# This is the default URL for view config server metadata
# http://localhost:9999/configserver/app/default

spring.datasource.url=jdbc:mysql://localhost:3306/microservice_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.show-sql=true
# Format SQL queries
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update


# Eureka Server location
eureka.client.service-url.defaultZone=http://localhost:8761/registry/eureka
