#=====================================================================================================================
# SPECIFIC ORDER-SERVICE CONFIGURATON FOR -----> DEFAULT <----- PROFILE ENVIRONMENT
#=====================================================================================================================
server.port =8082
server.servlet.context-path= /order
