#=====================================================================================================================
# SPECIFIC PAYMENT-SERVICE CONFIGURATON FOR -----> DEFAULT <----- PROFILE ENVIRONMENT
#=====================================================================================================================

server.port =8083
server.servlet.context-path= /payment
