#=====================================================================================================================
# SPECIFIC SERVICE-REGISTRY CONFIGURATON FOR -----> DEFAULT <----- PROFILE ENVIRONMENT
#=====================================================================================================================
server.port=8761

server.servlet.context-path=/registry

#Stoping self registration as a client

eureka.client.fetch-registry=false
eureka.client.register-with-eureka=false
