#=====================================================================================================================
# SPECIFIC USER-SERVICE CONFIGURATON FOR -----> DEFAULT <----- PROFILE ENVIRONMENT
#=====================================================================================================================

server.port =8081
server.servlet.context-path= /user
# Register this application with Eureka
eureka.client.register-with-eureka=true

# Fetch information about other services
eureka.client.fetch-registry=true
